@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package golemknights.tinkersgolem.content.modifiers.golem;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;