@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package golemknights.tinkersgolem.events;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;