@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package golemknights.tinkersgolem.modifiers.tool;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;