@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package golemknights.tinkersgolem.modifiers.golem;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;