@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package golemknights.tinkersgolem.content.modifiers.slime;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;